### ISSUE TITLE
Implement backbone of Evita contract

### ISSUE THREAD

**Issue by KirillTemnov** [EvitaDAO/tokenomics#1]
Use https://wizard.openzeppelin.com/ as boilerplate

- [ ] Use OpenZeppelin upgradeable ERC20 as base class
- [ ] add Ownable to proxy/contract
- [ ] minting by owner
- [ ] burning by all
- [ ] handle sending to zero address as burning

**Comment by Evgen123** [comment]
0x84B95447CAbC9BF99B1CE360AeEF91f9f3DdF156

**Comment by Evgen123** [comment]
I insert  in Evita.sol:
Ownable.sol
ERC20.sol
..and Context.sol  IERC20.sol  IERC20Metadata.sol  - they are needed for

**Comment by Evgen123** [comment]
files:

https://dropmefiles.com/LGKop

**Comment by Evgen123** [comment]
I did move all additions SOLs OpenZeppelin to one folder UTILS (the original code, not depend on changing in the future)
but we can use 
import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

**Comment by Evgen123** [comment]
new one

[0x1757cc80Cf9aFd4507842DfB6F9D371d54Fc0dcC](https://rinkeby.etherscan.io/address/0x1757cc80Cf9aFd4507842DfB6F9D371d54Fc0dcC)
