### ISSUE TITLE
//1 Project skeleton

### ISSUE THREAD

**Issue by developerkunal** [EvitaDAO/tokenomics#10]
# Project
- initialize yarn project
- add core dependencies, 
    "@nomiclabs/hardhat-ethers"
    "@nomiclabs/hardhat-etherscan"
    "@nomiclabs/hardhat-waffle"
    "@openzeppelin/contracts"
     "@openzeppelin/contracts-upgradeable"
    "chai"
    "ethereum-waffle"
    "ethers"
    "hardhat"
- init hardhat project
# Github Actions 
- set up running tests on push in github

# Contract 
- burning tokens by owner of tokens
- simple tests for burning
-  handle sending to zero address as burning
- tests

**Comment by quantum13** [comment]
done in #9
