### ISSUE TITLE
Implement backbone of EvitaDAO contract

### ISSUE THREAD

**Issue by KirillTemnov** [EvitaDAO/tokenomics#2]
Use https://wizard.openzeppelin.com/ as boilerplate

- [ ] Use OpenZeppelin upgradeable ERC721 as base class
- [ ] Add Ownable to proxy/contract

**Comment by Evgen123** [comment]
0xf85C442D66f85e3c00E00DA657f6340edb51EcE7

[Rinkeby](https://rinkeby.etherscan.io/address/0xf85C442D66f85e3c00E00DA657f6340edb51EcE7)

**Comment by Evgen123** [comment]
from OpenZeppelin - https://github.com/viniul/openzeppelin-solidity/tree/master/contracts

I insert in Evita.sol:
Ownable.sol
ERC721.sol
..and Address.sol IERC20.sol  Context.sol  ERC165.sol  IERC165.sol  IERC721.sol   IERC721Metadata.sol   IERC721Receiver.sol   Strings.sol    - they are needed for contracts above

**Comment by Evgen123** [comment]
files:

https://dropmefiles.com/s97Yy

**Comment by Evgen123** [comment]
new one contract 
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/token/ERC721/ERC721.sol";

https://rinkeby.etherscan.io/address/0xF6785ab466043F2A36f489fb8f14e396B2CfAD26

**Comment by quantum13** [comment]
closed since we re-decomposed tasks
